"""empty message

Revision ID: 1242c96bf857
Revises: 261dd33b4a5a
Create Date: 2017-03-16 14:08:52.065474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1242c96bf857'
down_revision = '261dd33b4a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adwords', sa.Column('optName', sa.String(length=100), nullable=True))
    op.add_column('adwords', sa.Column('rebate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adwords', 'rebate')
    op.drop_column('adwords', 'optName')
    # ### end Alembic commands ###
