"""empty message

Revision ID: 23dd072bab56
Revises: 
Create Date: 2017-04-06 15:01:23.774897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23dd072bab56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountRebate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountId', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('accountName', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('rebate', sa.Float(), nullable=True),
    sa.Column('updateTime', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'offer', sa.Column('emailaccount', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'offer', 'emailaccount')
    op.drop_table('accountRebate')
    # ### end Alembic commands ###
