"""empty message

Revision ID: 261dd33b4a5a
Revises: 6c714b36f727
Create Date: 2017-03-15 19:29:09.520330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '261dd33b4a5a'
down_revision = '6c714b36f727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataDetail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('campaignId', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cvr', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('cpi', sa.Float(), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('rebate', sa.Float(), nullable=True),
    sa.Column('updateTime', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(u'campaignrelations_ibfk_1', 'campaignRelations', type_='foreignkey')
    op.drop_column(u'campaignRelations', 'conversions')
    op.drop_column(u'campaignRelations', 'cpi')
    op.drop_column(u'campaignRelations', 'updateTime')
    op.drop_column(u'campaignRelations', 'ctr')
    op.drop_column(u'campaignRelations', 'revenue')
    op.drop_column(u'campaignRelations', 'profit')
    op.drop_column(u'campaignRelations', 'country')
    op.drop_column(u'campaignRelations', 'offer_id')
    op.drop_column(u'campaignRelations', 'cpc')
    op.drop_column(u'campaignRelations', 'cvr')
    op.drop_column(u'campaignRelations', 'rebate')
    op.drop_column(u'campaignRelations', 'cost')
    op.drop_column(u'campaignRelations', 'date')
    op.drop_column(u'campaignRelations', 'impressions')
    op.drop_column(u'campaignRelations', 'clicks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'campaignRelations', sa.Column('clicks', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'campaignRelations', sa.Column('impressions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'campaignRelations', sa.Column('date', mysql.VARCHAR(length=100), nullable=True))
    op.add_column(u'campaignRelations', sa.Column('cost', mysql.FLOAT(), nullable=True))
    op.add_column(u'campaignRelations', sa.Column('rebate', mysql.FLOAT(), nullable=True))
    op.add_column(u'campaignRelations', sa.Column('cvr', mysql.FLOAT(), nullable=True))
    op.add_column(u'campaignRelations', sa.Column('cpc', mysql.FLOAT(), nullable=True))
    op.add_column(u'campaignRelations', sa.Column('offer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'campaignRelations', sa.Column('country', mysql.VARCHAR(length=100), nullable=True))
    op.add_column(u'campaignRelations', sa.Column('profit', mysql.FLOAT(), nullable=True))
    op.add_column(u'campaignRelations', sa.Column('revenue', mysql.FLOAT(), nullable=True))
    op.add_column(u'campaignRelations', sa.Column('ctr', mysql.FLOAT(), nullable=True))
    op.add_column(u'campaignRelations', sa.Column('updateTime', mysql.VARCHAR(length=100), nullable=True))
    op.add_column(u'campaignRelations', sa.Column('cpi', mysql.FLOAT(), nullable=True))
    op.add_column(u'campaignRelations', sa.Column('conversions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'campaignrelations_ibfk_1', 'campaignRelations', 'offer', ['offer_id'], ['id'])
    op.drop_table('dataDetail')
    # ### end Alembic commands ###
