"""empty message

Revision ID: 281a0ae9265f
Revises: 
Create Date: 2017-03-09 14:48:22.642027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281a0ae9265f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rebate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountId', sa.String(length=100), nullable=True),
    sa.Column('scale', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rebate')
    # ### end Alembic commands ###
