"""empty message

Revision ID: 2e0ab3b97608
Revises: 
Create Date: 2016-12-29 18:03:00.838880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0ab3b97608'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=100), nullable=False),
    sa.Column('accessToken', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advertisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=10000), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('advertise_series', sa.String(length=100), nullable=False),
    sa.Column('advertise_groups', sa.String(length=100), nullable=False),
    sa.Column('createdTime', sa.String(length=100), nullable=False),
    sa.Column('updateTime', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertisers')
    op.drop_table('token')
    # ### end Alembic commands ###
