"""empty message

Revision ID: 38ae12698928
Revises: 5b525a2f1b5a
Create Date: 2017-03-29 11:32:50.176685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ae12698928'
down_revision = '5b525a2f1b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rebate', sa.Column('companyName', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rebate', 'companyName')
    # ### end Alembic commands ###
