"""Initial migration

Revision ID: 3fd2175256d1
Revises: 
Create Date: 2017-01-06 16:43:25.256568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3fd2175256d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group')
    op.alter_column('advertisers', 'advertise_groups',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('advertisers', 'advertise_series',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('history', 'KPI',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('history', 'contract_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('offer', 'KPI',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('offer', 'app_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('offer', 'app_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('offer', 'authorized',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('offer', 'distribution',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('offer', 'email_tempalte',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('offer', 'email_time',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text(u"''"))
    op.alter_column('offer', 'email_users',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('offer', 'named_rule',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('offer', 'os',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('offer', 'package_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('offer', 'period',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('offer', 'preview_link',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('offer', 'remark',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('offer', 'settlement',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('offer', 'track_link',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(u'permissions_ibfk_1', 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'group_id')
    op.add_column('timePrice', sa.Column('offer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'timePrice', 'offer', ['offer_id'], ['id'])
    op.drop_index('name', table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('name', 'user', ['name'], unique=True)
    op.drop_constraint(None, 'timePrice', type_='foreignkey')
    op.drop_column('timePrice', 'offer_id')
    op.add_column('permissions', sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'permissions_ibfk_1', 'permissions', 'group', ['group_id'], ['id'])
    op.alter_column('offer', 'track_link',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('offer', 'settlement',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('offer', 'remark',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('offer', 'preview_link',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('offer', 'period',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('offer', 'package_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('offer', 'os',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('offer', 'named_rule',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('offer', 'email_users',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('offer', 'email_time',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text(u"''"))
    op.alter_column('offer', 'email_tempalte',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('offer', 'distribution',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('offer', 'authorized',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('offer', 'app_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('offer', 'app_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('offer', 'KPI',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('history', 'contract_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('history', 'KPI',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('advertisers', 'advertise_series',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('advertisers', 'advertise_groups',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_table('group',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'group_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
