"""empty message

Revision ID: 54012f6433c5
Revises: 
Create Date: 2017-02-10 16:55:06.787531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54012f6433c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaignRelations', sa.Column('account_id', sa.String(length=100), nullable=False))
    op.drop_constraint(u'campaignrelations_ibfk_1', 'campaignRelations', type_='foreignkey')
    op.drop_column('campaignRelations', 'offer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaignRelations', sa.Column('offer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'campaignrelations_ibfk_1', 'campaignRelations', 'offer', ['offer_id'], ['id'])
    op.drop_column('campaignRelations', 'account_id')
    # ### end Alembic commands ###
