"""empty message

Revision ID: 5b525a2f1b5a
Revises: b7b54c511244
Create Date: 2017-03-29 10:15:16.572486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b525a2f1b5a'
down_revision = 'b7b54c511244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rebate', sa.Column('accountName', sa.String(length=100), nullable=True))
    op.add_column('rebate', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('rebate', sa.Column('bank_account', sa.String(length=100), nullable=True))
    op.add_column('rebate', sa.Column('concordat_code', sa.String(length=100), nullable=True))
    op.add_column('rebate', sa.Column('createdTime', sa.String(length=100), nullable=True))
    op.add_column('rebate', sa.Column('keywords', sa.String(length=100), nullable=True))
    op.add_column('rebate', sa.Column('platform', sa.String(length=100), nullable=True))
    op.add_column('rebate', sa.Column('remark', sa.String(length=100), nullable=True))
    op.add_column('rebate', sa.Column('status', sa.String(length=100), nullable=True))
    op.drop_column('rebate', 'accountId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rebate', sa.Column('accountId', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('rebate', 'status')
    op.drop_column('rebate', 'remark')
    op.drop_column('rebate', 'platform')
    op.drop_column('rebate', 'keywords')
    op.drop_column('rebate', 'createdTime')
    op.drop_column('rebate', 'concordat_code')
    op.drop_column('rebate', 'bank_account')
    op.drop_column('rebate', 'address')
    op.drop_column('rebate', 'accountName')
    # ### end Alembic commands ###
