"""empty message

Revision ID: 5f121d0a13d4
Revises: 1242c96bf857
Create Date: 2017-03-17 09:27:38.896316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f121d0a13d4'
down_revision = '1242c96bf857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaignAppName', sa.Column('optName', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaignAppName', 'optName')
    # ### end Alembic commands ###
