"""empty message

Revision ID: 62c6a313a609
Revises: 6f6d895d07d5
Create Date: 2017-02-24 14:41:30.904406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c6a313a609'
down_revision = '6f6d895d07d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adwordsGeo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('countryNumber', sa.String(length=100), nullable=True),
    sa.Column('countryName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adwordsGeo')
    # ### end Alembic commands ###
