"""empty message

Revision ID: 651e7e467380
Revises: 5f121d0a13d4
Create Date: 2017-03-18 15:31:17.699952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651e7e467380'
down_revision = '5f121d0a13d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataDetail', sa.Column('optName', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataDetail', 'optName')
    # ### end Alembic commands ###
