"""empty message

Revision ID: 66a0b0839cfd
Revises: b1b619e76f58
Create Date: 2017-02-25 14:28:30.626528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a0b0839cfd'
down_revision = 'b1b619e76f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('is_UAC', sa.Integer(), nullable=True),
    sa.Column('campaignId', sa.Integer(), nullable=False),
    sa.Column('campaignName', sa.String(length=150), nullable=False),
    sa.Column('impressions', sa.String(length=100), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('conversions', sa.String(length=100), nullable=True),
    sa.Column('cpc', sa.String(length=100), nullable=True),
    sa.Column('cvr', sa.String(length=100), nullable=True),
    sa.Column('cpi', sa.String(length=100), nullable=True),
    sa.Column('ctr', sa.String(length=100), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adwords')
    # ### end Alembic commands ###
