"""empty message

Revision ID: 68a4194a9152
Revises: 
Create Date: 2017-01-09 16:05:20.012409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a4194a9152'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shorthand', sa.String(length=100), nullable=False),
    sa.Column('british', sa.String(length=100), nullable=False),
    sa.Column('chinese', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('company_address', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.String(length=100), nullable=False),
    sa.Column('last_datetime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name'),
    sa.UniqueConstraint('customer_code')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permissions_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=100), nullable=False),
    sa.Column('accessToken', sa.String(length=10000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('passwd', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('last_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('permissions_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('contract_type', sa.String(length=100), nullable=True),
    sa.Column('contract_num', sa.String(length=100), nullable=False),
    sa.Column('contract_scale', sa.Float(), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('package_name', sa.String(length=100), nullable=True),
    sa.Column('app_name', sa.String(length=100), nullable=True),
    sa.Column('app_type', sa.String(length=100), nullable=True),
    sa.Column('preview_link', sa.String(length=100), nullable=True),
    sa.Column('track_link', sa.String(length=100), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('startTime', sa.String(length=100), nullable=False),
    sa.Column('endTime', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('daily_budget', sa.Float(), nullable=True),
    sa.Column('daily_type', sa.String(length=100), nullable=True),
    sa.Column('total_budget', sa.Float(), nullable=True),
    sa.Column('total_type', sa.String(length=100), nullable=True),
    sa.Column('distribution', sa.String(length=100), nullable=True),
    sa.Column('authorized', sa.String(length=100), nullable=True),
    sa.Column('named_rule', sa.String(length=100), nullable=True),
    sa.Column('KPI', sa.String(length=100), nullable=True),
    sa.Column('settlement', sa.String(length=100), nullable=True),
    sa.Column('period', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.String(length=100), nullable=True),
    sa.Column('email_time', sa.String(length=100), nullable=True),
    sa.Column('email_users', sa.String(length=100), nullable=True),
    sa.Column('email_tempalte', sa.Integer(), nullable=True),
    sa.Column('createdTime', sa.String(length=100), nullable=False),
    sa.Column('updateTime', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timePrice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advertisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=10000), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('advertise_series', sa.String(length=100), nullable=True),
    sa.Column('advertise_groups', sa.String(length=100), nullable=True),
    sa.Column('createdTime', sa.String(length=100), nullable=False),
    sa.Column('updateTime', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('createdTime', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('country_price', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('daily_budget', sa.Float(), nullable=True),
    sa.Column('daily_type', sa.String(length=100), nullable=True),
    sa.Column('total_budget', sa.Float(), nullable=True),
    sa.Column('total_type', sa.String(length=100), nullable=True),
    sa.Column('KPI', sa.String(length=100), nullable=True),
    sa.Column('contract_type', sa.String(length=100), nullable=True),
    sa.Column('contract_scale', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('advertisers')
    op.drop_table('timePrice')
    op.drop_table('offer')
    op.drop_table('user_role')
    op.drop_table('user_permissions')
    op.drop_table('user')
    op.drop_table('token')
    op.drop_table('role_permissions')
    op.drop_table('role')
    op.drop_table('permissions')
    op.drop_table('customers')
    op.drop_table('country')
    # ### end Alembic commands ###
