"""empty message

Revision ID: 6c714b36f727
Revises: 0da987a0fff3
Create Date: 2017-03-15 16:30:04.558097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c714b36f727'
down_revision = '0da987a0fff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaignRelations', sa.Column('clicks', sa.Integer(), nullable=True))
    op.add_column('campaignRelations', sa.Column('conversions', sa.Integer(), nullable=True))
    op.add_column('campaignRelations', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('campaignRelations', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('campaignRelations', sa.Column('cpc', sa.Float(), nullable=True))
    op.add_column('campaignRelations', sa.Column('cpi', sa.Float(), nullable=True))
    op.add_column('campaignRelations', sa.Column('ctr', sa.Float(), nullable=True))
    op.add_column('campaignRelations', sa.Column('cvr', sa.Float(), nullable=True))
    op.add_column('campaignRelations', sa.Column('date', sa.String(length=100), nullable=True))
    op.add_column('campaignRelations', sa.Column('impressions', sa.Integer(), nullable=True))
    op.add_column('campaignRelations', sa.Column('offer_id', sa.Integer(), nullable=True))
    op.add_column('campaignRelations', sa.Column('profit', sa.Float(), nullable=True))
    op.add_column('campaignRelations', sa.Column('rebate', sa.Float(), nullable=True))
    op.add_column('campaignRelations', sa.Column('revenue', sa.Float(), nullable=True))
    op.add_column('campaignRelations', sa.Column('updateTime', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'campaignRelations', 'offer', ['offer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaignRelations', type_='foreignkey')
    op.drop_column('campaignRelations', 'updateTime')
    op.drop_column('campaignRelations', 'revenue')
    op.drop_column('campaignRelations', 'rebate')
    op.drop_column('campaignRelations', 'profit')
    op.drop_column('campaignRelations', 'offer_id')
    op.drop_column('campaignRelations', 'impressions')
    op.drop_column('campaignRelations', 'date')
    op.drop_column('campaignRelations', 'cvr')
    op.drop_column('campaignRelations', 'ctr')
    op.drop_column('campaignRelations', 'cpi')
    op.drop_column('campaignRelations', 'cpc')
    op.drop_column('campaignRelations', 'country')
    op.drop_column('campaignRelations', 'cost')
    op.drop_column('campaignRelations', 'conversions')
    op.drop_column('campaignRelations', 'clicks')
    # ### end Alembic commands ###
