"""empty message

Revision ID: 90fe0e520492
Revises: 281a0ae9265f
Create Date: 2017-03-09 15:24:11.468596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fe0e520492'
down_revision = '281a0ae9265f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datas', sa.Column('rebate', sa.Float(), nullable=True))
    op.add_column('datas', sa.Column('updateTime', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datas', 'updateTime')
    op.drop_column('datas', 'rebate')
    # ### end Alembic commands ###
