"""empty message

Revision ID: 9b7bde97568f
Revises: 651e7e467380
Create Date: 2017-03-18 16:03:38.051306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b7bde97568f'
down_revision = '651e7e467380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optimization')
    op.add_column('user', sa.Column('optName', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'optName')
    op.create_table('optimization',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('simple', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('createdTime', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
