"""empty message

Revision ID: b1b619e76f58
Revises: c65497a772ae
Create Date: 2017-02-25 14:21:42.204166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1b619e76f58'
down_revision = 'c65497a772ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adwords', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adwords', 'country')
    # ### end Alembic commands ###
