"""empty message

Revision ID: b5678e675400
Revises: 
Create Date: 2016-12-29 13:50:02.132957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5678e675400'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('advertise_series', sa.String(length=100), nullable=False),
    sa.Column('advertise_groups', sa.String(length=100), nullable=False),
    sa.Column('createdTime', sa.String(length=100), nullable=False),
    sa.Column('updateTime', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('group')
    op.alter_column('history', 'country',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text(u"''"))
    op.alter_column('history', 'country_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.drop_constraint(u'permissions_ibfk_1', 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'group_id')
    op.add_column('user', sa.Column('last_datetime', sa.DateTime(), nullable=True))
    op.drop_index('name', table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('name', 'user', ['name'], unique=True)
    op.drop_column('user', 'last_datetime')
    op.add_column('permissions', sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'permissions_ibfk_1', 'permissions', 'group', ['group_id'], ['id'])
    op.alter_column('history', 'country_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('history', 'country',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text(u"''"))
    op.create_table('group',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'group_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('advertisers')
    # ### end Alembic commands ###
