"""empty message

Revision ID: c868e10dabf6
Revises: 
Create Date: 2017-02-23 16:49:12.437046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c868e10dabf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('is_UAC', sa.Boolean(), nullable=True),
    sa.Column('campaignId', sa.Integer(), nullable=False),
    sa.Column('campaignName', sa.String(length=150), nullable=False),
    sa.Column('impressions', sa.String(length=100), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('conversions', sa.String(length=100), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adwords')
    # ### end Alembic commands ###
