"""empty message

Revision ID: cf8b1b01b8c3
Revises: 23dd072bab56
Create Date: 2017-04-06 15:15:42.302298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8b1b01b8c3'
down_revision = '23dd072bab56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accountRebate', sa.Column('date', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accountRebate', 'date')
    # ### end Alembic commands ###
