"""empty message

Revision ID: e54fc5ecef52
Revises: 6ba1ad93bd6e
Create Date: 2017-03-29 13:51:36.044762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54fc5ecef52'
down_revision = '6ba1ad93bd6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rebate', sa.Column('companyName', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rebate', 'companyName')
    # ### end Alembic commands ###
