"""empty message

Revision ID: fb9376adc009
Revises: 
Create Date: 2017-04-01 12:38:23.248404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9376adc009'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailaccounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emailaccounts')
    # ### end Alembic commands ###
