"""empty message

Revision ID: fec0a52801ea
Revises: 66a0b0839cfd
Create Date: 2017-02-28 10:53:06.619546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec0a52801ea'
down_revision = '66a0b0839cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('bank_account', sa.String(length=100), nullable=False))
    op.add_column('customers', sa.Column('concordat_code', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'concordat_code')
    op.drop_column('customers', 'bank_account')
    # ### end Alembic commands ###
